export const products = [
  {
    name: "Onions",
    img: "../public/photos/onions.jpg",
    price: 20,
    category: "vegetables",
    description: "White onions because the purple one is more expensive",
    stock: 10,
  },
  {
    name: "Lettuce",
    img: "../public/photos/lettuce.jpg",
    price: 15,
    category: "vegetables",
    description: "Fresh green lettuce to make any salad",
    stock: 10,
  },
  {
    name: "Potatoes",
    img: "../public/photos/potatoes.jpg",
    price: 25,
    category: "vegetables",
    description: "Everybody's best friend, yummy potatoes",
    stock: 50,
  },
  {
    name: "Strawberries",
    img: "../public/photos/strawberries.jpg",
    price: 20,
    category: "fruits",
    description: "Sweet and juicy strawberries",
    stock: 20,
  },
  {
    name: "Coconuts",
    img: "../public/photos/coconuts.jpg",
    price: 40,
    category: "fruits",
    description: "Refreshing tropical fruit that can be a drink or a snack",
    stock: 15,
  },
  {
    name: "Passion Fruits",
    img: "../public/photos/passionfurit.jpg",
    price: 35,
    category: "fruits",
    description: "Ugly looking but delicious on the inside",
    stock: 5,
  },
  {
    name: "Pears",
    img: "../public/photos/pears.jpg",
    price: 15,
    category: "fruits",
    description: "The softest and most delicious pears you've ever tasted",
    stock: 30,
  },
  {
    name: "Cowboy Hat",
    img: "../public/photos/cowboyhat.jpg",
    price: 150,
    category: "headwear",
    description: "Do you want to feel like a cowboy while farming, buy this!",
    stock: 1,
  },
];
